# Site settings
title: Marvin Guerra
email: marvin@marvinguerra.com
description: > # this means to ignore newlines until "baseurl:"
  Llama, llama, hack
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://marvinguerra.com" # the base hostname & protocol for your site
twitter_username: SenorLlama
github_username:  SenorLlama

# Build settings
markdown: kramdown
